version: '3.5'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=statbot

  statbot:
    image: jchristhub/strinking-statbot:latest
    depends_on:
      - db
    secrets:
      - statbot_config
    command: bash -c "sleep 5; python3 -m statbot  -U postgres://postgres:postgres@db/statbot /run/secrets/statbot_config"

  web:
    build: .
    image: jchristhub/strinking-site:latest
    environment:
      - DEBUG=1
      - LOG_LEVEL=INFO
      - PGSQL_NO_SSL=yes
      - PGSQL_URL=postgres://postgres:postgres@db/statbot
      - SECRET_KEY=imnotsecret
    ports:
      - "8000:8000"
    depends_on:
      - db
      - statbot
    command: "./docker/serve.sh"

secrets:
  statbot_config:
    file: ./docker/statbot_config.yaml


# vim: shiftwidth=2
