# Generated by Django 2.0.3 on 2018-04-09 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_change_content_to_markup_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-pub_datetime']},
        ),
        migrations.AlterField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=markupfield.fields.MarkupField(help_text='Markdown with fenced code blocks (GFM) is supported.', rendered_field=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(help_text='Give your guide a readable and descriptive title.', max_length=100),
        ),
    ]
