# Generated by Django 2.0.3 on 2018-04-13 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guides', '0003_change_ordering_add_help_texts_apply_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='editors',
            field=models.ManyToManyField(help_text='Add editors to your Guide. You will always stay the sole owner of it, and can add and remove editors freely.', related_name='_guide_editors_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
