# Generated by Django 2.0.3 on 2018-05-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_guide_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='editors',
        ),
    ]
