# Generated by Django 2.0.3 on 2018-05-17 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_add_guide_permissions_to_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guide',
            name='overview',
            field=models.CharField(help_text='A short overview of the guide, used for preview information and in OGP tags.', max_length=200),
        ),
    ]
